/**
 * AI-Powered Hint System Models
 *
 * Provides intelligent, natural language hints using:
 * 1. Chrome's Built-in AI (Gemini Nano) - PRIMARY (on-device, free, private)
 * 2. Heuristic analysis - FALLBACK (when Web AI unavailable)
 *
 * Uses Chrome's window.ai API for privacy-preserving, offline-capable AI
 */

import { GridCell, LixsoSymbol, LTile, LTileOrientation } from './game.models';

export type HintLevel = 'beginner' | 'intermediate' | 'advanced' | 'expert';
export type HintType = 'next-move' | 'strategy' | 'pattern' | 'mistake' | 'encouragement';

/**
 * AI-generated hint with natural language explanation
 */
export interface AIHint {
  id: string;
  type: HintType;
  level: HintLevel;

  // The hint content
  title: string;
  explanation: string;
  suggestedTile?: LTile;
  suggestedPosition?: { row: number; col: number };

  // AI metadata
  confidence: number; // 0-1, how confident the AI is
  reasoning?: string; // Step-by-step reasoning
  alternatives?: AlternativeMove[];

  // Quality metrics
  moveQuality: number; // 0-100, how good is this move
  difficultyReduction: number; // How much easier will the puzzle become

  // Generated by
  source: 'chrome-ai' | 'heuristic' | 'hybrid';
  generatedAt: Date;
  processingTime?: number; // milliseconds
}

/**
 * Alternative move suggestions
 */
export interface AlternativeMove {
  tile: LTile;
  position: { row: number; col: number };
  quality: number; // 0-100
  reasoning: string;
}

/**
 * Board state analysis for AI
 */
export interface BoardAnalysis {
  currentState: GridCell[][];
  emptyCount: number;
  filledCount: number;
  prefillCount: number;

  // Pattern analysis
  clusters: ColorCluster[];
  openSpaces: OpenSpace[];
  constraints: Constraint[];

  // Difficulty metrics
  complexity: number; // 0-100
  estimatedMoves: number;
  solutionCount: number; // 1 = unique, >1 = multiple solutions

  // Player context
  errorCount: number;
  hintsUsed: number;
  timeElapsed: number;
}

/**
 * Color cluster detection
 */
export interface ColorCluster {
  symbol: LixsoSymbol;
  cells: { row: number; col: number }[];
  size: number;
  isProblematic: boolean; // true if creating adjacency issues
}

/**
 * Open space where tiles can be placed
 */
export interface OpenSpace {
  startRow: number;
  startCol: number;
  width: number;
  height: number;
  possibleTiles: LTile[];
}

/**
 * Constraint that limits tile placement
 */
export interface Constraint {
  type: 'adjacency' | 'boundary' | 'prefill';
  affectedCells: { row: number; col: number }[];
  description: string;
}

/**
 * Chrome AI (Gemini Nano) API request format
 */
export interface ChromeAIHintRequest {
  boardState: string; // Serialized board
  playerLevel: HintLevel;
  context: PlayerContext;
  requestType: HintType;
}

/**
 * Player context for personalized hints
 */
export interface PlayerContext {
  gamesPlayed: number;
  winRate: number;
  averageTime: number;
  preferredDifficulty: number;
  recentMistakes: string[];
  learningStyle?: 'visual' | 'verbal' | 'logical';
}

/**
 * Chrome AI (Gemini Nano) API response format
 */
export interface ChromeAIHintResponse {
  hint: string;
  reasoning: string;
  suggestedMove?: {
    symbol: LixsoSymbol;
    orientation: LTileOrientation;
    anchorRow: number;
    anchorCol: number;
  };
  confidence: number;
  alternatives?: Array<{
    move: {
      symbol: LixsoSymbol;
      orientation: LTileOrientation;
      anchorRow: number;
      anchorCol: number;
    };
    quality: number;
    reason: string;
  }>;
}

/**
 * Chrome AI Capabilities detection
 */
export interface ChromeAICapabilities {
  available: boolean;
  promptAPI: boolean;
  translationAPI: boolean;
  summarizationAPI: boolean;
  languageDetectionAPI: boolean;
}

/**
 * Hint cache entry for performance
 */
export interface HintCacheEntry {
  boardHash: string;
  hint: AIHint;
  cachedAt: Date;
  hits: number;
}

/**
 * AI hint service configuration
 */
export interface AIHintConfig {
  // Chrome AI settings
  useChromeAI: boolean; // Primary: use built-in Chrome AI
  temperature: number; // 0-1, creativity level
  maxOutputLength: number; // max characters in response

  // Caching
  enableCache: boolean;
  cacheTimeout: number; // milliseconds

  // Fallback
  enableHeuristics: boolean; // Fallback when Chrome AI unavailable
  fallbackOnError: boolean;

  // Performance
  timeout: number; // milliseconds before fallback
}

/**
 * Heuristic hint (offline fallback)
 */
export interface HeuristicHint {
  suggestedTile: LTile;
  position: { row: number; col: number };
  reasoning: string;
  patterns: DetectedPattern[];
}

/**
 * Detected pattern in the board
 */
export interface DetectedPattern {
  type: 'corner' | 'edge' | 'center' | 'isolated' | 'cluster';
  location: { row: number; col: number };
  significance: number; // 0-1
  suggestion: string;
}

/**
 * AI hint generation statistics
 */
export interface HintStatistics {
  totalHints: number;
  chromeAIHints: number;
  heuristicHints: number;
  averageConfidence: number;
  cacheHitRate: number;
  averageResponseTime: number; // milliseconds
  chromeAIAvailability: number; // percentage of time Chrome AI was available
}

/**
 * Learning path tracking
 */
export interface LearningPath {
  playerId: string;
  currentLevel: HintLevel;

  // Progress metrics
  conceptsMastered: string[];
  strugglingWith: string[];
  recommendedFocus: string[];

  // Adaptive hint configuration
  adaptiveLevel: HintLevel;
  showReasoning: boolean;
  showAlternatives: boolean;

  // History
  hintHistory: AIHint[];
  improvementRate: number; // 0-1
}
