# Auto-assign configuration
# Automatically assigns reviewers to PRs

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - kluth  # Replace with actual GitHub username(s)

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

# A list of keywords to be skipped for reviewer assignment
skipKeywords:
  - wip
  - WIP
  - draft
